### ISSUE TITLE
Add CI for Pull Requests

### ISSUE THREAD

**Issue by victornoel** [artipie/ppom#22]
It seems that to do a release, there are some checks done on the deployed pom.xml. If there are errors, they are not caught with CI during a PR, so it makes everybody loose their time.

See #21 for an example of this.

We should add some CI to validate PRs.

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) I'm not managing this repo, remove the [webhook](https://github.com/artipie/ppom/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/ppom` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@rultor release, tag=`0.3.3`

**Comment by g4s8** [comment]
@victornoel thanks, it should be fixed in #23

**Comment by victornoel** [comment]
@g4s8 thx!

**Comment by 0crat** [comment]
I'm not managing `artipie/ppom` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
