### ISSUE TITLE
Logging dependencies

### ISSUE THREAD

**Issue by Nimmaster** [artipie/ppom#5]
- Add facade (`slf4j`)
- Add impl (`logback` or `log4j2`)
- Add config file

**Comment by 0crat** [comment]
@nimmaster[/z](https://www.0crat.com/u/nimmaster) I'm not managing this repo, remove the [webhook](https://github.com/artipie/ppom/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/ppom` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/ppom` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
